- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Add repository
    yum_repository:
      name: nginx repo
      description: nginx repo install
      baseurl: http://nginx.org/packages/mainline/amzn2/$releasever/$basearch/
      gpgkey: https://nginx.org/keys/nginx_signing.key

  - name: getting os name 
    shell: 'cat /etc/os-release | grep -i id_like | cut -d "=" -f2 '
    register: os

  - name: install nginx  in amazon machine
    when: os.stdout ==  '"centos rhel fedora"'
    yum:               
      name: nginx
      state: present

  - name: install nginx  in ubuntu machine
    when: os.stdout == "debian"
    apt:
      name: nginx
      state: present
      
